In [2]:
import numpy as np

an_array = np.array([3, 33, 333])

print(an_array)
print(type(an_array))

[  3  33 333]
<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [6]:
print(an_array[2])


333


In [8]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [14]:
ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [20]:
ex3 = np.eye(4,4)
print(ex3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [23]:
ex5 = 2*np.random.random((2,2))
print(ex5)

[[0.87924376 1.52968748]
 [0.69223576 0.17206297]]


In [24]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [26]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [31]:
print(a_slice[0,1])
print(an_array[1,1])

13
22


In [43]:
a_slice[0,0] = 500
print(a_slice)
print()
print(an_array)
# observe that 500 appears in respective positions of both a_slice as well as an_array
a_slice[0,0] = 12
print()
print(a_slice)
print()
print(an_array)

[[500  13]
 [ 22  23]]

[[ 11 500  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]]

[[12 13]
 [22 23]]

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [45]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [46]:
for row,col in zip(col_rank1, col_rank2):
    print(row, ',', col)

12 , [12]
22 , [22]
32 , [32]


In [48]:
a = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print(a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [50]:
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [51]:
for row,col in zip(col_indices,row_indices):
    print(row, ',', col)

0 , 0
1 , 1
2 , 2
0 , 3


In [58]:
print('Values at those indices: ', a[row_indices, col_indices])

Values at those indices:  [3011 3022 3033 3041]


[[3011   12   13]
 [  21 3022   23]
 [  31   32 3033]
 [3041   42   43]]
