In [2]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
filter = (a > 3)
filter

array([[False, False],
       [False,  True],
       [ True,  True]])

In [4]:
print(int(a[filter]))

TypeError: only size-1 arrays can be converted to Python scalars

In [8]:
print(a[a < 5])

[1 2 3 4]


In [9]:
print(a[a % 2 == 0])

[2 4 6]


In [12]:
a[a % 2 == 0] += 100
print(a)

[[  1 202]
 [  3 204]
 [  5 206]]


In [13]:
x = np.array([[1, 2], [6, 8]], dtype=np.float)
print(x)

[[1. 2.]
 [6. 8.]]


In [15]:
print(x.dtype)

float64
