In [4]:
#Basic statistical operations:

import numpy as np

In [5]:
#setup a random 2 x 5 matrix

arr = 10 * np.random.randn(2,5)
print(arr)

[[ 13.4312645   15.4464914  -25.20851002   4.73750622 -13.39374082]
 [-15.774688    -7.45882487  -6.2338241   -5.80652423   7.30000406]]


In [6]:
# mean for all the entries of arr
print(arr.mean())

-3.296084586882833


In [7]:
# compute the means by row by axis = 1

print(arr.mean(axis = 1))

[-0.99739774 -5.59477143]


In [8]:
# compute the means by column by axis = 0

print(arr.mean(axis = 0))

[ -1.17171175   3.99383327 -15.72116706  -0.53450901  -3.04686838]


In [9]:
# sum all the elements
print(arr.sum())

-32.96084586882833


In [12]:
# compute the medians by column by axis = 0

print(np.median(arr, axis = 0))

# compute the medians by column by axis = 0

print(np.median(arr, axis = 1))

[ -1.17171175   3.99383327 -15.72116706  -0.53450901  -3.04686838]
[ 4.73750622 -6.2338241 ]


In [17]:
unsorted = np.random.randn(10)
print(unsorted)

[-1.79250594 -0.14589843  0.27205664  0.63643475 -1.00380071  0.87559628
 -0.87531187 -2.38523897  0.36247437 -0.33456472]


In [18]:
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-2.38523897 -1.79250594 -1.00380071 -0.87531187 -0.33456472 -0.14589843
  0.27205664  0.36247437  0.63643475  0.87559628]

[-1.79250594 -0.14589843  0.27205664  0.63643475 -1.00380071  0.87559628
 -0.87531187 -2.38523897  0.36247437 -0.33456472]


In [20]:
b = np.array([1,2,3,4,2,2,3,7,0,8,7,9,0])
print(np.unique(b))

[0 1 2 3 4 7 8 9]


In [21]:
s1 = np.array(['desk', 'lamp', 'chair'])
s2 = np.array(['bulb', 'desk', 'chair'])
print(s1, s2)

['desk' 'lamp' 'chair'] ['bulb' 'desk' 'chair']


In [22]:
print(np.intersect1d(s1,s2))

['chair' 'desk']


In [23]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [24]:
print(np.setdiff1d(s1,s2))

['lamp']


In [25]:
print(np.setdiff1d(s2,s1))

['bulb']


In [26]:
print(np.setdiff1d(s1,s1))

[]


In [27]:
print(np.in1d(s1,s2))     # which elements of s1 is also in s2

[ True False  True]
