In [5]:
import numpy as np

an_array = np.array([3, 33, 333])     #create a rank 1 array

print(type(an_array))
print(an_array)

<class 'numpy.ndarray'>
[  3  33 333]


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[1])

33


In [5]:
an_array[0] = 5
print(an_array)

[  5  33 333]


In [7]:
rank2 = np.array([[1, 2],[3, 4]])
print(rank2)

[[1 2]
 [3 4]]


In [8]:
print(rank2.shape)

(2, 2)


In [9]:
import numpy as np
ex1 = np.zeros((2,2))
print(ex1)


[[0. 0.]
 [0. 0.]]
