In [1]:
# numpy broadcasting
import numpy as np

a = np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
b = np.array([1, 0, 2])
print(b)

[1 0 2]


In [3]:
print(a+b)     # look although the matrices are not of thre same dimension or order they still add up


[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [9]:
add_col = np.array([[0,1,2,3]])
add_col = add_col.T     # .T transposes the matrix
print(add_col)

[[0]
 [1]
 [2]
 [3]]


In [10]:
print(a+ add_col)    # again the matrices add up even when the dimensions are not comparable

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [11]:
add_scalar = np.array([1])
print(a + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
